### PR TITLE
feat: UI for `/users` route

### LINKED ISSUE #92: [FEAT] :sparkles: create UI for `/users` page
### Description

all the logic part is implemented only UI needs to get worked upon

### Anything else?

take table UI reference from [tailwind docs](https://tailwindcss.com/docs/table-layout)

### PR DESCRIPTION
**Pull request by JohnnyOhms**
### Description
I created UI for users page
styled the user page Table using Tailwind css styled approach.
its a full width responsive tailwind css table from there DOC

### Checklist:

- [x] This pull request follow our contribution guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (postman and swagger)
- [x] I have written tests for the code
- [x] I have updated .env.example file for new .env variables

### What is current behavior?
Unstyled user page

Closes #92

### What is new behavior?

Styled User page with tailwind css table

tailwind css table layout

### Breaking Changes?

None

_Pls review and merge, open for corrections, Branch up till date_ @aayushchugh

### CODE REVIEW

**Review by aayushchugh — CHANGES_REQUESTED** [review]
@JohnnyOhms  sorry but I forgot to mention before that we need light color theme so please change the theme to light. every thing else looks great

**Review by is-it-ayush — COMMENTED** [review]
Looks Cool! Please make the corrections suggested by @aayushchugh. Thanks for contributing.

**Comment by JohnnyOhms** [comment]
Thanks for the correction, working o the Light theme now @is-it-ayush  @aayushchugh

**Comment by JohnnyOhms** [comment]
**light mode table added on the Users page, ready to be reviewed and merge. am open for corrections**
@aayushchugh  @is-it-ayush 
Screenshot 2022-12-23 204113

**Review by aayushchugh — APPROVED** [review]
Nice! Thanks for the PR

**Pull request merged**
